[project]
name = "retrieval-based-voice-conversion-webui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "onnx>=1.19.1",
    "onnxruntime>=1.23.2",
]
